enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
serviceControlPolicies: []
taggingPolicies: []
backupPolicies: []
chatbotPolicies: []
resourceControlPolicies: []
declarativePolicies: []
