#!/usr/bin/env bats

setup() {
  REPOSITORY_ROOT="$(cd -- "${BATS_TEST_DIRNAME}/.." && pwd)"
  source "${REPOSITORY_ROOT}/deploy/scripts/common.sh"
}

@test "Phase 0 evidence contract validates and denies a live-validator claim" {
  python3 - "${REPOSITORY_ROOT}" <<'PY'
import json
import pathlib
import sys
from jsonschema import Draft202012Validator, ValidationError

root = pathlib.Path(sys.argv[1])
schema = json.loads((root / "deployment/schemas/deployment-evidence.schema.json").read_text())
fixture = {
    "schemaVersion": 2, "gate": "phase0-offline", "generatedAt": "2000-01-01T00:00:00Z",
    "repositoryValidationOnly": True, "liveValidatorRan": False,
    "checks": [{"number": n, "name": f"check-{n}", "status": "passed"} for n in range(1, 9)],
    "digests": {f"digest-{n}": "0" * 64 for n in range(1, 12)},
}
Draft202012Validator(schema).validate(fixture)
fixture["liveValidatorRan"] = True
try:
    Draft202012Validator(schema).validate(fixture)
except ValidationError:
    pass
else:
    raise AssertionError("schema accepted a live-validator claim")
PY
}

@test "generated evidence validates when present" {
  evidence="${REPOSITORY_ROOT}/build/deployment-evidence.json"
  if [[ ! -f "${evidence}" ]]; then
    skip "evidence is generated by check 8"
  fi
  python3 - "${REPOSITORY_ROOT}" "${evidence}" <<'PY'
import json
import pathlib
import sys
from jsonschema import Draft202012Validator
root = pathlib.Path(sys.argv[1])
schema = json.loads((root / "deployment/schemas/deployment-evidence.schema.json").read_text())
Draft202012Validator(schema).validate(json.loads(pathlib.Path(sys.argv[2]).read_text()))
PY
}
