mandatoryAccounts:
  - name: Management
    description: GovCloud organization management account
    email: management+test-turtle-1@sunstonesecure.com
    organizationalUnit: Root
  - name: LogArchive
    description: AWS Control Tower and platform log archive account
    email: logarchive+test-turtle-1@sunstonesecure.com
    organizationalUnit: Security
  - name: Audit
    description: AWS Control Tower security, Config aggregator, and audit account
    email: audit+test-turtle-1@sunstonesecure.com
    organizationalUnit: Security
workloadAccounts: []
